// Generated by scripts/sync-engine.mjs from packages/engine/UPSTREAM.json. Do not edit.
export const ENGINE_UPSTREAM = {
  repo: "Roni-1997/verdict",
  commit: "79f3ed255dbd9a628b01d9a38eb149f2116cbffb",
  files: [
    {
      "local": "packages/engine/src/research-core.ts",
      "upstream": "src/research/research-core.ts",
      "sha256": "13ad72d878b58791fbe4a7cf1fe70ea2f165a935ee7736ac51a8b629a8e6b688"
    },
    {
      "local": "packages/engine/src/playbooks.ts",
      "upstream": "src/research/playbooks.ts",
      "sha256": "f92dcf911f0e94c6fb8e0ed6d43e7d8c04a988a1e49e33964288a58cc9691f6c"
    },
    {
      "local": "packages/engine/src/hl-shape.ts",
      "upstream": "src/live/hl-shape.ts",
      "sha256": "4082598e8708b7ddddc3b3556ff0b5412626856b06002c83df7f3e8566612531"
    }
  ],
} as const;
