// Generated by scripts/sync-api-contract.mjs from packages/core/api-contract/UPSTREAM.json. Do not edit.
/** The Verdict API contract (docs/api/openapi.json in the app repository) the hosted tools in remote.ts were built against. */
export const API_CONTRACT = {
  repo: "Roni-1997/verdict",
  commit: "352b2352918cfb9d0616ae19cd4f80346e1d44a9",
  files: [
    {
      "local": "packages/core/api-contract/openapi.json",
      "upstream": "docs/api/openapi.json",
      "sha256": "714ce5f91f9129a3007ccb3746f3a2c3bf890a7c9115f85d16eab1b4582cb8b2"
    }
  ],
} as const;
