#!/usr/bin/env node
// Copy the cross-venue engine from the Verdict app repository at a pinned commit into
// packages/engine/src, byte for byte, and record the pin in packages/engine/UPSTREAM.json.
// Nothing is copied by hand: every file comes from the GitHub contents API at the pinned
// commit. Re-run with --commit <sha> to move the pin; then run check-engine-drift.mjs.
//
//   node scripts/sync-engine.mjs [--commit <sha>]
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const upstreamPath = resolve(root, 'packages/engine/UPSTREAM.json');
const generatedPath = resolve(root, 'packages/engine/src/upstream.ts');

const DEFAULTS = {
  repo: 'Roni-1997/verdict',
  commit: '79f3ed255dbd9a628b01d9a38eb149f2116cbffb',
  files: [
    { local: 'packages/engine/src/research-core.ts', upstream: 'src/research/research-core.ts' },
    { local: 'packages/engine/src/playbooks.ts', upstream: 'src/research/playbooks.ts' },
    { local: 'packages/engine/src/hl-shape.ts', upstream: 'src/live/hl-shape.ts' },
  ],
};

function readExisting() {
  try {
    return JSON.parse(readFileSync(upstreamPath, 'utf8'));
  } catch {
    return null;
  }
}

function argValue(flag) {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

export function fetchGithubFile(repo, path, commit) {
  const res = spawnSync('gh', ['api', `repos/${repo}/contents/${path}?ref=${commit}`], { encoding: 'utf8' });
  if (res.error) throw new Error(`gh not available: ${res.error.message}`);
  if (res.status !== 0) throw new Error(`gh api failed for ${path}: ${res.stderr.trim() || res.stdout.trim()}`);
  const body = JSON.parse(res.stdout);
  if (body.encoding !== 'base64' || typeof body.content !== 'string') throw new Error(`unexpected contents response for ${path}`);
  return { bytes: Buffer.from(body.content, 'base64'), blobSha: body.sha };
}

export function sha256(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

export function gitBlobSha1(bytes) {
  return createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex');
}

function main() {
  const existing = readExisting();
  const repo = existing?.repo ?? DEFAULTS.repo;
  const commit = argValue('--commit') ?? existing?.commit ?? DEFAULTS.commit;
  const files = (existing?.files ?? DEFAULTS.files).map((f) => ({ local: f.local, upstream: f.upstream }));
  const out = [];
  for (const f of files) {
    const { bytes, blobSha } = fetchGithubFile(repo, f.upstream, commit);
    if (gitBlobSha1(bytes) !== blobSha) throw new Error(`blob sha mismatch for ${f.upstream}: content did not decode to the blob GitHub reported`);
    const target = resolve(root, f.local);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, bytes);
    out.push({ local: f.local, upstream: f.upstream, bytes: bytes.length, gitBlobSha1: blobSha, sha256: sha256(bytes) });
    process.stdout.write(`${f.local}  ${bytes.length} bytes  sha256 ${out.at(-1).sha256}\n`);
  }
  const record = { repo, commit, syncedAt: new Date().toISOString(), files: out };
  writeFileSync(upstreamPath, `${JSON.stringify(record, null, 2)}\n`);
  writeFileSync(
    generatedPath,
    [
      '// Generated by scripts/sync-engine.mjs from packages/engine/UPSTREAM.json. Do not edit.',
      'export const ENGINE_UPSTREAM = {',
      `  repo: ${JSON.stringify(repo)},`,
      `  commit: ${JSON.stringify(commit)},`,
      `  files: ${JSON.stringify(out.map((f) => ({ local: f.local, upstream: f.upstream, sha256: f.sha256 })), null, 2).replace(/\n/g, '\n  ')},`,
      '} as const;',
      '',
    ].join('\n'),
  );
  process.stdout.write(`pinned ${repo}@${commit} in ${upstreamPath}\n`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
